language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION sourcecodeJVM/test:run sourcecodeJS/test:run
scala:
  - 2.10.6
  - 2.11.8
  - 2.12.0
  - 2.13.0-M1
jdk:
  - openjdk7
  - oraclejdk8
matrix:
  exclude:
    - scala: 2.12.0
      jdk: openjdk7
    - scala: 2.13.0-M1
      jdk: openjdk7
sudo: false
